server:
  port: 9001    # 指定端口

spring:
  application:
    name: tensquare-base   # 模块名
  datasource:   # 配置数据源
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/tensquare_base?characterEncoding=utf-8
    username: root
    password: root
  jpa:      # 配置jpa
    database: mysql
    show-sql: true
  rabbitmq:
    host: yun
    port: 5672
    username: squ
    password: squ
    virtual-host: /squ
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:6868/eureka/  # http://127.0.0.1:6868/eureka/
  instance:
    prefer-ip-address: true
ip: 127.0.0.222


