server:
  port: 9008
spring:
  application:
    name: tensquare-user #指定服务名
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/tensquare_user?characterEncoding=utf-8
    username: root
    password: root
  jpa:
    database: MySQL
    show-sql: true
  redis:
    host: yun
  rabbitmq:
    host: yun
    port: 5672
    username: squ
    password: squ
    virtual-host: /squ
jwt:
  config:
    # 加盐
    key: lmzw
    ttl: 3600000
eureka:
  client:
    serviceUrl:
     defaultZone: http://127.0.0.1:6868/eureka/
  instance:
    prefer-ip-address: true
